### ISSUE TITLE
Amazon Resource Name configuration failed

### ISSUE THREAD

**Issue by tonylampada** [bastillion-io/Bastillion-EC2#73]
After starting bastillion-ec2, running it for the first time and adding a key to `/manage/saveIAMRole.ktrl`, I get the error:

Error!
Amazon Resource Name configuration failed

![image](https://user-images.githubusercontent.com/218821/87195567-13d60280-c2d0-11ea-9abe-2eec39dd0b74.png)

The java logs say:

```
[startBastillionEC2.sh INFO] restoring JCEKS file from persistent storage
2020-07-10 19:55:00.956:INFO::main: Logging initialized @1371ms to org.eclipse.jetty.util.log.StdErrLog
2020-07-10 19:55:01.772:INFO:oejs.Server:main: jetty-9.4.29.v20200521; built: 2020-05-21T17:20:40.598Z; git: 77c232aed8a45c818fd27232278d9f95a021095e; jvm 9.0.4+12-Debian-4
2020-07-10 19:55:01.835:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/bastillion/jetty/webapps/] at interval 1
2020-07-10 19:55:13.353:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=9980ms
2020-07-10 19:55:13.860:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2020-07-10 19:55:13.860:INFO:oejs.session:main: No SessionScavenger set, using defaults
2020-07-10 19:55:13.862:INFO:oejs.session:main: node0 Scavenging every 660000ms
2020-07-10 19:55:17.568:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@57bc27f5{/,file:///opt/bastillion/jetty/bastillion/,AVAILABLE}{/opt/bastillion/jetty/bastillion}
2020-07-10 19:55:17.805:INFO:oejs.AbstractConnector:main: Started ServerConnector@4cbc2e3b{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-07-10 19:55:17.807:INFO:oejs.Server:main: Started @18223ms
2020-07-10 19:55:36,733 INFO  LoginAudit - admin (187.75.157.141) - Authentication Success
2020-07-10 19:57:24,600 INFO  LoginAudit - admin (187.75.157.141) - Authentication Success
java.lang.IllegalArgumentException: Access key cannot be null.
	at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
	at io.bastillion.manage.util.AWSClientConfig.getCredentials(AWSClientConfig.java:133)
	at io.bastillion.manage.control.IAMRoleKtrl.validateSaveIAMRole(IAMRoleKtrl.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at loophole.mvc.base.BaseKontroller.execute(BaseKontroller.java:163)
	at loophole.mvc.base.DispatcherServlet.execute(DispatcherServlet.java:75)
	at loophole.mvc.base.DispatcherServlet.doPost(DispatcherServlet.java:57)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1411)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at loophole.mvc.filter.SecurityFilter.doFilter(SecurityFilter.java:96)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at loophole.mvc.filter.CSRFFilter.doFilter(CSRFFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at io.bastillion.common.filter.AuthFilter.doFilter(AuthFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Any idea what I might be doing wrong? :-)

**Comment by tonylampada** [comment]
OK found a solution.
Had to set `accessKey` and `secretKey` as mentioned in the README (but not in [the docs!](https://www.bastillion.io/docs/bastillion-ec2/iam_role/))

Also the access Key and secret key are from a user that was added as a principal on the trust relation of the bastillion IAM role, like this

![image](https://user-images.githubusercontent.com/218821/87223506-fe0a2100-c353-11ea-9e24-8c41e515a92c.png)

This solved the error above. I'm still having trouble though. I'll create another issue if I get stuck again.
